name: zs
person:
  name: lsi
  age: 18
student: {name: ww,age: 29}
city:
  - bj
  - tj
  - zz

teacher:
  - name: jk
    age: 22
  - name: lc
    age: 23
te: [{name: jk,age: 23},{name: zs,age: 24}]
server:
  port: 8082